Order process
ittopshamb/AridonShopBackend pull request #6
Opened 2023-03-29 22:11 UTC by NodiraShaporeva

2023-03-30 09:22 UTC, rodion-m commented
Нодира, это весь код по фиче процессинга заказа или еще что-то будет?

2023-03-30 11:26 UTC, NodiraShaporeva commented
> Нодира, это весь код по фиче обработки заказа или еще что-то будет?

Нет, не весь, я еще не написала ничего в контроллере. И вообще, думаю, надо перенести ShippingDetails в Models. Но еще пока не пробовала. Еще думаю, надо переписать EmailSender через MailKit, но пока тоже не знаю как это буду делать. Задача оказалась для меня сложнее, чем я думала) сложно сориентироваться в чужом коде - писать в контроллерах и сервисах, которые ты не писала сама - проще создать дополнительные отдельные классы и т.п. Хотя я думаю, это неправильно.

2023-04-04 14:39 UTC, rodion-m commented
@NodiraShaporeva Нодира, уже гораздо лучше. Недостатки пометил - поправьте по-возможности.
Так же будет очень в тему если вы напишите тест для метода размещения заказа, можно новым PR'ом.

2023-04-06 21:19 UTC, rodion-m requested changes

2023-04-06 21:19 UTC, rodion-m commented on backend/OnlineStore.Domain/Services/SmtpMailKitEmailSender.cs
> +            await _smtpClient.ConnectAsync(_smtpConfig.Host, _smtpConfig.Port);
Этот метод тоже поддерживает отмену

2023-04-06 21:19 UTC, rodion-m commented on backend/OnlineStore.Domain/Services/SmtpMailKitEmailSender.cs
> +            await _smtpClient.AuthenticateAsync(_smtpConfig.UserName, _smtpConfig.Password);
Этот метод тоже поддерживает отмену

2023-04-06 21:19 UTC, rodion-m commented on backend/OnlineStore.WebApi/Controllers/OrderController.cs
> +        var order = await _orderService.CreateAndReplaceOrder(accountId, request.City, request.Address, cancellationToken);
Все-таки не нравится мне это название, неточное оно и непонятное. Предлагаю альтернативу: PlaceOrderAndCreateNew

2023-04-07 10:10 UTC, merged

2023-04-07 10:11 UTC, rodion-m commented
LGTM